const quotes = {
 shrek: [
"Once upon a time there was a lovely princess. But she had an enchantment upon her of a fearful sort which could only be broken by love's first kiss. She was locked away in a castle guarded by a terrible fire-breathing dragon. Many brave knights had attempted to free her from this dreadful prison, but non prevailed. She waited in the dragon's keep in the highest room of the tallest tower for her true love and true love's first kiss. Like that's ever gonna happen. What a load of -.",
"Yes, well, actually, that would be a giant. Now, ogres, oh they're much worse. They'll make a suit from your freshly peeled skin...",
"They'll shave your liver. Squeeze the jelly from your eyes! Actually, it's quite good on toast.",
'This is the part where you run away.',
'And stay out! "Wanted. Fairytale creatures."',
'Oh, really? You and what army?',
"Are you talkin' to... me? Whoa!",
"Oh, that's great. Really.",
"Now, why don't you go celebrate your freedom with your own friends? Hmm?",
'Why are you following me?',
"Stop singing! It's no wonder you don't have any friends.",
'Listen, little donkey. Take a look at me. What am I?',
`No! I'm an ogre! You know, "Grab your torch and pitchforks." Doesn't that bother you? `,
'That would be my home.',
'I like my privacy.',
'Okay! Okay! But one night only.',
'What are you...No! No!',
'I thought I told you to stay outside!',
'Enough! What are you doing in my house? Hey!',
'Oh, no, no, no. Dead broad off the table!',
"I live in a swamp. I put up signs. I'm a terrifying ogre! What do I have to do get a little privacy?",
'Oh, no. No! No!',
'What are you doing in my swamp?!!',
"All right, get out of here. All of you, move it! Come on! Let's go! Hapaya! Hapaya! Hey! Quickly. Come on! No, no! No, no. Not there! Not there! Oh!",
'All right. Who knows where this... "Farquaad" guy is?',
'Does anyone else know where to find him? Anyone at all?',
"Okay, fine. Attention all...fairy tale things. Do not get comfortable. Your welcome is officially worn out. In fact, I'm gonna see this guy Farquaad right now and get you all off my land and back where you came from! Oh! You! You're comin' with me.",
'What did I say about singing?',
'All right, hum it.',
"So, that must be Lord Farquaad's castle.",
"Do you think maybe he's compensating for something?",
'Hey, you! (',
"Wait a second. Look, I'm not gonna eat you. I just- - I just - -",
"It's quiet. Too quiet. Where is everybody?",
'No. No. No, no, no! No.',
"All right. You're going the right way for a smacked bottom.",
"Ah, that's not very nice. It's just a donkey.",
'Oh, hey! Now come on! Hang on now.',
"Can't we just settle this over a pint?",
'No? All right then. Come on!',
"Oh, yeah! Ah! Ah! Thank you! Thank you very much! I'm here till Thursday. Try the veal! Ha, ha!",
"Quest? I'm already on a quest. A quest to get my swamp back.",
'Yeah, my swamp! Where you dumped those fairy tale creatures!',
'Exactly the way it was?',
'And the squatters?',
'What kind of quest?',
"You know, maybe there's a good reason donkeys shouldn't talk.",
'Oh, I know what. Maybe I could have decapitated an entire village and put their heads on a pike, gotten a knife, cut open their spleen and drink their fluids. Does that sound good to you?',
"For your information, there's a lot more to ogres than people think.",
'Example? Okay, um, ogres are like onions.',
'Yes - - No!',
'No! Layers! Onions have layers. Ogres have layers! Onions have layers. You get it? We both have layers.',
"I don't care... what everyone likes. Ogres are not like cakes.",
'No! You dense, irritating, miniature beast of burden! Ogres are like onions! End of story. Bye-bye. See ya later.',
'You know, I think I preferred your humming.',
"Believe me, Donkey, if it was me, you'd be dead. It's brimstone. We must be getting close.",
"Sure, it's big enough, but look at the location.",
"Wait a second. Donkeys don't have sleeves.",
"Oh you can't tell me you're afraid of heights.",
"Come on, Donkey. I'm right here beside ya, okay? For emotional support. We'll just tackle this thing together one little baby step at a time.",
"Just keep moving. And don't look down.",
"But you're already halfway.",
"Okay, fine. I don't have time for this. You go back.",
"Just, Donkey - - Let's have a dance then, shall me?",
"Oh, I'm sorry. Do what? Oh, this?",
'Yes? Yes, do it. Okay.',
"You said do it! I'm doin' it.",
"That'll do, Donkey. That'll do.",
'Inside, waiting for us to rescue her.',
'Donkey, two things, okay? Shut... up. Now go over there and see if you can find any stairs.',
'The princess will be up the stairs in the highest room in the tallest tower.',
'I read it in a book once.',
"Well, at least we know where the princess is, but where's the...",
'Donkey, look out!',
'Are you Princess Fiona?',
"Oh, that's nice. Now let's go!",
"Yeah, sorry, lady. There's no time.",
"You've had a lot of time to plan this, haven't you?",
"I don't think so.",
"It's on my to-do list. Now come on!",
'Yeah, right before they burst into flame.',
'Well, I have to save my ass.',
'One of a kind.',
"Yeah, it's getting him to shut up that's the trick.",
"Okay, you two, head for the exit! I'll take care of the dragon.",
'I have helmet hair.',
"No, no, you wouldn't - - 'st.",
"What? That wasn't in the job description.",
"Let's just say I'm not your type, okay?",
"Look. I really don't think this is a good idea.",
"I'm not going to.",
'Okay! Easy. As you command,,,your Highness.',
'Oh, you were expecting Prince Charming.',
"Princess, I was sent to rescue you by Lord Farquaad, okay? He's the one who wants to marry you.",
'Good question. You should ask him that when we get there.',
"Look princess you're not making my job any easier.",
"Hey! I'm no one's messenger boy, all right? I'm a delivery boy.",
"Ya comin', Donkey?",
"Let me put it this way, princess. Men of Farquaad's stature are in,,,,short supply.",
`Yeah, well, maybe you're right, princess. But I'll let you do the "measuring" when you see him tomorrow. `,
"No, that'll take longer. We can keep going.",
"Hey, come on. I'm scarier than anything we're going to see in this forest.",
'Hey! Over here.',
'Homey touches? Like what?',
'I just--you know - - Oh, come on. I was just kidding.',
"The stars don't tell the future, Donkey. They tell stories. Look, there's Bloodnut, the Flatulent. You can guess what he's famous for.",
"No, look. There he is, and there's the group of hunters running away from his stench.",
'You know, Donkey, sometimes things are more than they appear. Hmm? Forget it.',
`We? Donkey, there's no "we". There's no "our". There's just me and my swamp. And the first thing I'm gonna do is build a ten-foot wall around my land. `,
'No, do ya think?',
'Never mind, Donkey.',
'No, this is one of those drop-it and leave-it alone things!',
'Why do you want to talk about it?',
"I'm not blocking.",
"Donkey, I'm warning you.",
'Oh! For the love of Pete!',
`Look, I'm not the one with the problem, okay? It's the world that seems to have a problem with me. People take one look at me and go. "Aah! Help! Run! A big, stupid, ugly ogre!" They judge me before they even know me. That's why I'm better off alone. `,
'Yeah, I know.',
"Well, there's, um, Gabby, the Small...and Annoying.",
"That's the moon.",
'Donkey, wake up.',
"What's all this about?",
"What? It's a compliment. Better out than in, I always say.",
"You know, you're not exactly what I expected.",
"Hey! That's my princess! Go find you own!",
'Hold the phone. Oh! Whoa, whoa, whoa. Hold on now. Where did that come from?',
'That! Back there. That was amazing! Where did you learn that?',
'What? Oh, would you look at that?',
"Donkey, I'm okay.",
'What are the flowers for?',
"Ow! Hey! Easy with the yankin'.",
"No, it's tender.",
"What you're doing is the opposite of help.",
'Look, time out.',
'Ow! Not good.',
'Nothing happened. We were just, uh...',
'There it is, princess. Your future awaits you.',
'Um, I, uh-- I guess we better move on.',
"You know, she's right. You look awful. Do you want to sit down ?",
"Who's hungry? I'll find us some dinner.",
'Uh, weed rat. Rotisserie style.',
"Well, they're also great in stews. Now, I don't mean to brag, but I make a mean weed rat stew.",
"Maybe you can come visit me in the swamp sometime. I'll cook all kind of stuff for you. Swamp toad soup, fish eye tartare -- you name it.",
'I, um, I was wondering...are you... Are you gonna eat that?',
"Oh, what are you talkin' about ?",
"You're crazy. I'm just bringing her back to Farquaad.",
"I--there's nothing to tell. Besides, even if I did tell her that, well, you know-- and I'm not sayin' I do, 'cause I don't -- she's a princess, and I'm...",
'Yeah. An ogre.',
'To get...more firewood.',
"Princess, I-- Uh, how's it going, first of all? Good? Um, good for me too. I'm okay. I saw this flower and thought of you because it's pretty and-- well, I don't really like it but I thought you might like it 'cause you're pretty. But I like you anyway. I'd-- uh, uh... I'm in trouble. Okay, here we go.",
'Perfect! Never been better.',
"You don't have to tell me anything, princess. I heard enough last night.",
'Oh, I understand. Like you said, "Who could love a hideous, ugly beast?"',
'Yeah? Well, it does.',
"Ah, right on time. Princess, I've brought you a little something.",
'As promised. Now hand it over.',
'Yeah? So what ?',
"I know you talked to her last night. You're great pals, aren't ya? Now, if you two are such good friends, why don't you follow her home?!",
"I told you, didn't I? You're not coming home with me. I live alone! My swamp! Me! Nobody else! Understand? Nobody! Especially useless, pathetic, annoying, talking donkeys!",
'Yeah. You know what? You thought wrong!',
'Donkey ? What are you doing ?',
"Well, yeah. But the wall's supposed to go around my swamp, not through it.",
'Oh! Your half. Hmm.',
'This is my swamp!',
'Let go, Donkey!',
"Well, I'm through with you.",
'Oh, yeah? Well, if I treated you so bad, how come you came back ?',
"Oh, yeah. You're right, Donkey. I forgive you... for stabbin' me in the back!",
'Love me? She said I was ugly, a hideous creature. I heard the two of you talking.',
"She wasn't talking about me? Well, then who was she talking about ?",
"Okay, look. I'm sorry, all right ? I'm sorry. I guess I am just a big, stupid, ugly ogre. Can you forgive me ?",
'So, um, what did Fiona say about me ?',
"The wedding! We'll never make it in time.",
'Aw, come here, you.',
'What are you talking about ?',
"I don't have time for this!",
'All right! Cut it out. When does this guy say the line ?',
'What do you see ?',
'Oh, for the love of Pete!',
"Hi, everyone. Havin' a good time, are ya? I love Duloc, first of all. Very clean.",
'Fiona! I need to talk to you.',
"But you can't marry him.",
"Because...because he's just marrying you so he can be king.",
"He's not your true love.",
'Well, I--uh--I mean...',
'Well, uh, that explains a lot.',
'Get out of my way! Fiona! Arrgh!',
'I -- I love you.',
'Fiona? Fiona. Are you all right ?',
'But you are beautiful. '
 ],
 donkey: [
"Please, don't turn me in. I'll never be stubborn again. I can change. Please! Give me another chance!",
'Hey! I can fly!',
"Ha, ha! That's right, fool! Now I'm a flying, talking donkey. You might have seen a housefly, maybe even a superfly but I bet you ain't never seen a donkey fly. Ha, ha! Uh-oh.",
"Can I say something to you? Listen, you was really, really, really somethin' back here. Incredible!",
"Yes. I was talkin' to you. Can I tell you that you that you was great back there? Man those guards! They thought they was all of that. Then you showed up and bam! They was trippin' over themselves like babes in the woods. That really made me feel good to see that.",
"Man, it's good to be free.",
"But, uh, I don't have any friends. And I'm not goin' out there by myself. Hey, wait a minute! I got a great idea! I'll stick with you. You're a mean, green, fightin' machine. Together we'll scare the spit out of anybody that crosses us.",
"Oh, wow! That was really scary. If you don't mind me sayin', if that don't work, your breath certainly will get the job done, 'cause you definitely need some Tic Tacs or something, 'cause you breath stinks! You almost burned the hair outta my nose, just like the time... then I ate some rotten berries. I had strong gases leaking out of my butt that day.",
"I'll tell you why. 'Cause I'm all alone, There's no one here beside me, My problems have all gone, There's no one to deride me, But you gotta have friends...",
'Wow. Only a true friend would be that cruelly honest.',
"Man, I like you. What's you name?",
`Shrek? Well, you know what I like about you, Shrek? You got that kind of "I-don't-care-what-nobody-thinks-of-me" thing. I like that. I respect that, Shrek. You all right. Whoa! Look at that. Who'd want to live in place like that? `,
"Oh! And it is lovely! Just beautiful. You know you are quite a decorator. It's amazing what you've done with such a modest budget. I like that boulder. That is a nice boulder. I guess you don't entertain much, do you?",
"You know, I do too. That's another thing we have in common. Like I hate it when you got somebody in your face. You'retrying to give them a hint, and they won't leave. And there's that big awkward silence you know ? Can I stay with you?",
'Can I stay with you, please?',
"Please! I don't wanna go back there! You don't know what it's like to be considered a freak. Well, maybe you do. But that's why we gotta stick together. You gotta let me stay! Please! Please!",
'Ah! Thank you!',
"This is gonna be fun! We can stay up late, swappin' manly stories, and in the mornin'... I'm makin' waffles.",
'Where do, uh, I sleep?',
"Oh, well, I guess that's cool. I mean, I don't know you, and you don't know me, so I guess outside is best, you know. Here I go. Good night. I mean, I do like the outdoors. I'm a donkey. I was born outside. I'll just be sitting by myself outside, I guess, you know. By myself, outside. I'm all alone...there's no one here beside me...",
'I am outside!',
"Hey, don't look at me. I didn't invite them.",
'Oh, I do. I know where he is!',
'Oh! Oh, pick me! Oh, I know! I know! Me, me!',
"All right, that's what I like to hear, man. Shrek and Donkey, two stalwart friends, off on a whirlwind big-city adventure. I love it!",
"On the road again. Sing it with me, Shrek. I can't wait to get on the road again.",
'Can I whistle?',
'Can I hum it?',
"But that's it. That's it right there. That's Duloc. I told ya I'd find it.",
"Uh-huh. That's the place.",
'Hey, wait. Wait up, Shrek.',
'Hey, look at this!',
"Wow! Let's do that again!",
'Sorry about that.',
'Hey, Shrek, tag me! Tag me!',
"Let me get this straight. You're gonna go fight a dragon and rescue a princess just so Farquaad will give you back a swamp which you only don't have because he filled it full of freaks in the first place. Is that about right?",
"I don't get it. Why don't you just pull some of that ogre stuff on him? Throttle him, lay siege to his fortress, grinds his bones to make your bread, the whole ogre trip.",
'Uh, no, not really, no.',
'They make you cry?',
"Oh, you leave them in the sun, they get all brown, start sproutin' little white hairs.",
'Oh, you both have layers. Oh. {Sniffs} You know, not everybody likes onions. Cake! Everybody loves cakes! Cakes have layers.',
`You know what else everybody likes? Parfaits. Have you ever met a person, you say, "Let's get some parfait," they say, "Hell no, I don't like no parfait"? Parfaits are delicious. `,
'Parfaits may be the most delicious thing on the whole damn planet.',
"Do you have a tissue or something? I'm making a mess. Just the word parfait makes me start slobbering.",
'Ohh! Shrek! Did you do that? You gotta warn somebody before you just crack one off. My mouth was open and everything.',
"Yeah, right, brimstone. Don't be talking about it's the brimstone. I know what I smell. It wasn't no brimstone. It didn't come off no stone neither.",
'Uh, Shrek? Uh, remember when you said that ogres have layers?',
"Well, I have a bit of a confession to make. Donkeys don't have layers. We wear our fear right out there on our sleeves.",
'You know what I mean.',
"No, I'm just a little uncomfortable about being on a rickety bridge over a boiling like of lava!",
'Okay, that makes me feel so much better.',
"Okay, don't look down. Don't look down. Don't look down. Keep on moving. Don't look down. Shrek! I'm lookin' down! Oh, God, I can't do this! Just let me off, please!",
'But I know that half is safe!',
'Shrek, no! Wait!',
"Don't do that!",
'No, Shrek! No! Stop it!',
"I'm gonna die. I'm gonna die. Shrek, I'm gonna die. Oh!",
'Cool. So where is this fire-breathing pain-in-the-neck anyway?',
"I was talkin' about the dragon, Shrek.",
"Oh, good. Me neither. 'Cause there's nothin' wrong with bein' afraid. Fear's a sensible response to an unfamiliar situation. Unfamiliar dangerous situation, I might add. With a dragon that breathes fire and eats knights and breathes fire. It sure doesn't mean you're a coward if you're a little scared. I sure as heck ain't no coward. I know that.",
"Stairs? I thought we was lookin' for the princess.",
"What makes you think she'll be there?",
"Cool. You handle the dragon. I'll handle the stairs. I'll find those stairs. I'll whip their butt too. Those stairs won't know which way they're goin'.",
"I'm gonna take drastic steps. Kick it to the curb. Don't mess with me. I'm the stair master. I've mastered the stairs. I wish I had a step right here. I'd step all over it.",
'Oh! Aah! Aah!',
"No. Oh, no, No! Oh, what large teeth you have. I mean white, sparkling teeth. I know you probably hear this all time from your food, but you must bleach, 'cause that is one dazzling smile you got there. Do I detect a hint of minty freshness?",
"And you know what else? You're-- You're a girl dragon! Oh, sure! I mean, of course you're a girl dragon. You're just reeking of feminine beauty. What's the matter with you? You got something in your eye?",
"Ohh. Oh. Oh. Man, I'd really love to stay, but you know, I'm, uh... I'm an asthmatic, and I don't know if it'd work out if you're gonna blow smoke rings and stuff. Shrek! No! Shrek! Shrek! Shrek!",
"Slow down. Slow down, baby, please. I believe it's healthy to get to know someone over a long period of time. Just call me old-fashioned. I don't want to rush into a physical relationship. I'm not ready for a commitment of, uh, this - - Magnitude really is the word I'm looking for. Magnitude-- Hey, that is unwanted physical contact. Hey, what are you doing ? Okay, okay. Let's just back up a little and take this one step at a time. We really should get to know each other first as friends or pen pals.",
"I'm on the road a lot, but I just love receiving cards -- I'd really love to stay, but -- Don't do that! That's my tail! That's my personal tail. You're gonna tear it off. I don't give permission-- What are you gonna do with that?",
'Hey, now. No way. No! No! No, no! No. No, no, no. No! Oh!',
"I hope you heard that. She called me a noble steed. She think I'm a steed.",
"Maybe it's a perk.",
'Hmm? With Shrek? You think- - Wait. Wait. You think that Shrek is you true love?',
' You think Shrek is your true love!',
'Well, so much for noble steed.',
"I'm right behind ya.",
"Okay, so here's another question. Say there's a woman that digs you, right, but you don't really like her that way. How do you let her down real easy so her feelings aren't hurt, but you don't get burned to a crisp and eaten? How do you do that?",
"Oh you're gonna love it there, Princess. It's beautiful!",
"I don't know. There are those who think...little of him.",
'Whoa! Time out, Shrek! Camp is definitely starting to sound good.',
"Shrek, we can do better than that. I don't think this is fit for a princess.",
'You want me to read you a bedtime story? Cause I will.',
'Shrek, what are you doing?!',
'Right. Yeah. Hey, can you tell my future from these stars?',
"That ain't nothin' but a bunch of little dots.",
'Hey, Shrek, what we gonna do when we get our swamp anyway?',
"You know, when we're through rescuing the princess.",
'You cut me deep, Shrek. You cut me real deep just now. You know what I think? I think this whole wall thing is just a way to keep somebody out.',
"Are you hidin' something?",
"Oh, this is another one of those onion things, isn't it?",
"Why don't you want to talk about it?",
'Why are you blocking?',
'Oh, yes, you are.',
'Who you trying to keep out?',
"Oh, now we're gettin' somewhere.",
"Hey what's your problem Shrek? What you got against the whole world anyway? Huh?",
"You know what? When we met, I didn't think you was just a big, stupid, ugly ogre.",
'So, uh, are there any donkeys up there?',
'Okay, okay, I see it now. The big shiny one, right there. That one there?',
'Mmm, yeah, you know I like it like that. Come on, baby. I said I like it...',
'Oh, good morning, Princess!',
"Well, it's no way to behave in front of a princess!",
"She's as nasty as you are.",
"Why? What's wrong?",
"Shrek's hurt! Shrek's hurt?! Oh, no, Shrek's gonna die!",
"You can't do this to me, Shrek. I'm too young for you to die! Keep your legs elevated! Turn your head and cough! Does anyone know the Heimlich?!",
"Blue flower, red thorns. Okay, I'm on it. Blue flower, red thorns. Don't die Shrek. If you see a long tunnel, stay away from the light!",
'Oh, yeah. Right. Blue flower, red thorns.',
"Blue flower, red thorns. Blue flower, red thorns. Blue flower, red thorns. This would be so much easier if I wasn't color-blind! Blue flower, red thorns.",
"Hold on, Shrek! I'm comin'!",
'Look, if you wanted to be alone, all you had to do was ask. Okay ?',
"Hey, what's that ? That's...is that blood ?",
"Yeah, I know. You know, Shrek thinks Lord Farquaad's compensating for something, which I think means he has a really...",
"What are you talking about? I'm fine.",
"I didn't want to say nothin', but I got this twinge in my neck, and when I turn my head like this, look, Ow! See ?",
"Hey, where you goin'? Oh, man, I can't feel my toes! I don't have any toes! I think I need a hug.",
"Man, isn't this romantic? Just look at that sunset.",
"Wait a minute. I see what's goin' on here.",
"You're afraid of the dark, aren't you ?",
"Don't feel bad, Princess. I used to be afraid of the dark, too, until -- Hey, no, wait. I'm still afraid of the dark.",
"Ohh! Now I really see what's goin' on here.",
"I don't even wanna hear it. Look, I'm an animal, and I got instincts. And I know you two were diggin' on each other. I could feel it.",
'Oh, come on, Shrek. Wake up and smell the pheromones. Just go on in and tell her how you feel.',
"Hey, where you goin' ?",
'Princess? Princess Fiona? Princess, where are you? Princess ?',
"It's very spooky in here. I ain't playing no games.",
'Shrek! Shrek! Shrek!',
'What did you do with the princess?!',
'Oh, my God! You ate the princess. Can you hear me ?',
"Listen, keep breathing! I'll get you out of there!",
'Shrek! Shrek! Shrek!',
"Princess? What happened to you? You're, uh, uh, uh, different.",
"Well, yeah! Was it something you ate? 'Cause I told Shrek those rats was a bad idea. You are what you eat, I said. Now--",
"What do you mean? Look, I ain't never seen you like this before.",
"Ah, that's beautiful. I didn't know you wrote poetry.",
"All right, all right. Calm down. Look, it's not that bad. You're not that ugly. Well, I ain't gonna lie. You are ugly. But you only look like this at night. Shrek's ugly 24/7.",
"Princess, how 'bout if you don't marry Farquaad ?",
"But, you know, um, you're kind of an orge, and Shrek-- well, you got a lot in common.",
'You at least gotta tell Shrek the truth.',
"What's the point of being able to talk if you gotta keep secrets ?",
"All right, all right. I won't tell him. But you should.",
"I just know before this is over, I'm gonna need a whole lot of serious therapy. Look at my eye twitchin'.",
"What'd I miss? What'd I miss ? Who said that? Couldn't have been the donkey.",
"Shrek, what are you doing? You're letting her get away!",
"Shrek, there's something about her you don't know. Look, I talked to her last night, She's - -",
'But, I thought...',
'I would think, of all people, you would recognize a wall when you see one.',
"It is around your half. See that's your half, and this is my half.",
'Yes, my half. I helped rescue the princess. I did half the work. I get half the booty. Now hand me that big old rock, the one that looks like your head.',
'No, you back off.',
'You let go.',
"Hey, hey, come back here. I'm not through with you yet.",
`Uh-uh. You know, with you it's always, "Me, me, me!" Well, guess what! Now it's my turn! So you just shut up and pay attention! You are mean to me. You insult me and you don't appreciate anything that I do! You're always pushing me around or pushing me away. `,
"Because that's what friends do! They forgive each other!",
"Ohh! You're so wrapped up in layers, onion boy, you're afraid of your own feelings.",
'There you are, doing it again just like you did to Fiona. All she ever do was like you, maybe even love you.',
"She wasn't talkin' about you. She was talkin' about, uh, somebody else.",
"Uh-uh, no way. I ain't saying anything. You don't wanna listen to me. Right? Right ?",
"Hey, that's what friends are for, right ?",
"What are you asking me for? Why don't you just go ask her ?",
"Ha-ha-ha! Never fear, for where, there's a will, there's a way and I have a way.",
"I guess it's just my animal magnetism. They both laugh.",
"All right, all right. Don't get all slobbery. No one likes a kiss ass. All right, hop on and hold on tight. I haven't had a chance to install the seat belts yet.",
"Go ahead, have some fun. If we need you, I'll whistle. How about that ? Shrek, wait, wait! Wait a minute! You wanna do this right, don't you ?",
`There's a line you gotta wait for. The preacher's gonna say, "Speak now or forever hold your peace." That's when you say, "I object!" `,
"Hey, wait. What are you doing? Listen to me! Look, you love this woman, don't you?",
'You wanna hold her ?',
'Then you got to, got to try a little tenderness. The chicks love that romantic crap!',
'We gotta check it out.',
"The whole town's in there.",
"They're at the altar.",
'Mother Fletcher! He already said it.',
"All right. Nobody move. I got a dragon here, and I'm not afraid to use it. I'm a donkey on the edge!",
'Celebrity marriages. They never last, do they ?',
'Go ahead, Shrek.',
'I was hoping this would be a happy ending.',
"Oh, that's funny. Oh. Oh. I can't breathe. I can't breathe. "
 ],
 fiona: [
'I am... awaiting a knight so bold as to rescue me.',
'But wait, Sir Knight! This be-ith our first meeting. Should it not be a wonderful, romantic moment?',
'Hey, wait. What are you doing? You know, you should sweep me off my feet out yonder window and down a rope onto your valiant steed.',
'But we have to savor this moment! You could recite an epic poem for me. A ballad? A sonnet! A limerick? Or something!',
'Can I at least know the name of my champion?',
'Sir Shrek. I pray that you take this favour as a token of my gratitude.',
"You didn't slay the dragon?!",
"But this isn't right! You were meant to charge in, sword drawn, banner flying. That's what all the other knights did!",
"That's not the point! Oh! Wait. Where are you going? The exit's over there.",
'Ugh. What kind of knight are you?',
"You did it! You rescued me! You're amazing. You're - - You're wonderful. You're... a little unorthodox I'll admit. But...thy deed is great, and thine heart is pure. I am eternally in your debt. And where would a brave knight be without his noble steed?",
'The battle is won. You may remove your helmet, good Sir Knight.',
"Please. I would'st look upon the face of my rescuer.",
'But, how will you kiss me?',
"No, it's destiny. Oh, you must know how it goes. A princess locked in a tower and beset by a dragon is rescued by a brave knight, and then they share true love's first kiss.",
'What is so funny?',
'Just take off the helmet.',
'Take it off.',
"Well, yes, actually. Oh, no. This is all wrong. You're not supposed to be an ogre!",
"Well then why didn't he come rescue me?",
'But I have to be rescued by my true love! Not by some ogre and his-- his pet.',
"I'm sorry, but your job is not my problem. You can tell Lord Farquaad that if he wants to rescue me properly, I'll be waiting for him right here.",
"You wouldn't dare. Put me down!",
'Ah! Put me down!',
'Put me down, or you will suffer the consequences! This is not dignified! Put me down!',
"You just tell her she's not your true love. Everyone knows what happens when you find your... Hey! The sooner we get to Duloc the better.",
"And what of my groom-to-be? Lord Farquaad? What's he like?",
"Stop it. Stop it, both of you. You're just jealous you can never measure up to a great ruler like Lord Farquaad.",
"Tomorrow? It'll take that long? Shouldn't we stop to make camp?",
"But there's... robbers in the woods.",
'I need to find somewhere to camp now!',
"No, no, it's perfect. It just needs a few homey touches.",
'A door? Well, gentlemen, I bid thee good night.',
'I said good night!',
'Good morning. Uh, how do you like your eggs?',
'You know, we kind of got off to a bad start yesterday. I wanted to make it up to you. I mean, after all, you did rescue me.',
"Well, eat up. We've got a big day ahead of us.",
"Well, maybe you shouldn't judge people before you get to know them.",
'Oh! Wait wait--what are you doing?!',
"Look, pal, I don't know who you think you are!",
'Man, that was annoying!',
'Uh, shall we?',
"Well... when one lives alone, uh, one has to learn these things in case there's a... there's an arrow in your butt!",
"Oh, no. This is all my fault. I'm so sorry.",
'Donkey! Calm down! If you want to help Shrek, run into the woods and find me a blue flower with red thorns.',
'For getting rid of Donkey.',
"Now you hold still, and I'll yank this thing out.",
"I'm sorry, but it has to come out.",
'Now, hold on.',
'Would you... Okay. What do you propose we do?',
"Okay. Okay. I can nearly see it. It's just about...",
"Sure. But, Shrek? I'm -- I'm worried about Donkey.",
"I mean, look at him. He doesn't look so good.",
"That's what they always say, and then next thing you know, you're on your back. Dead.",
"Uh, you know, I'll make you some tea.",
"I'll get the firewood.",
'Mmm. This is good. This is really good. What is this ?',
'No kidding. Well, this is delicious.',
"I guess I'll be dining a little differently tomorrow night.",
"I'd like that.",
"Sunset?! Oh, no! I mean, it's late. I-It's very late.",
"Yes! Yes, that's it. I'm terrified. You know, I'd better go inside.",
"No, it's okay. It's okay.",
"Donkey, I'm the princess.",
"It's me, in this body.",
'This is me.',
"I'm ugly, okay ?",
"No! I -- I've been this way as long as I can remember.",
`It only happens when sun goes down. "By night one way, by day another. This shall be the norm... until you find true love's first kiss... and then take love's true form." `,
"It's a spell. When I was a little girl, a witch cast a spell on me. Every night I become this. This horrible, ugly beast! I was placed in a tower to await the day my true love would rescue me. That's why I have to marry Lord Farquaad tomorrow before the sun sets and he sees me like this.",
"But Donkey, I'm a princess, and this is not how a princess is meant to look.",
"I have to. Only my true love's kiss can break the spell.",
`I can't just marry whoever I want. Take a good look at me, Donkey. I mean, really, who can ever love a beast so hideous and ugly? "Princess" and "ugly" don't go together. That's why I can't stay here with Shrek. `,
'My only chance to live happily ever after is to marry my true love.',
"Don't you see, Donkey? That's just how it has to be. It's the only way to break the spell.",
"No! You can't breathe a word. No one must ever know.",
"Promise you won't tell. Promise!",
"I tell him, I tell him not. I tell him, I tell him not...I tell him! Shrek! Shrek, there's something I want...",
'Shrek! Are you all right ?',
"I --I don't -- There's something I have to tell you.",
'You heard what I said ?',
"I thought you'd understand.",
"But I thought that wouldn't matter to you.",
'Lord Farquaad? Oh, no, no. Forgive me, my lord, for I was just saying a short......farewell.',
"No, you're right. It doesn't.",
'Lord Farquaad, I accept. Nothing would make --',
"I mean, uh, why wait? Let's get married today. Before the sun sets.",
`Excuse me. Could we just skip ahead to the "I do's" ? `,
'What are you doing here ?',
"Oh, now you wanna talk? It's a little late for that, so if you'll excuse me--",
'And why not ?',
'And what do you know about true love ?',
'Shrek, is this true ?',
"By night one way, by day another. I wanted to show you before.",
'No, no! Shrek!',
'No, let go of me! Shrek!',
'I love you too.',
" Well, yes. But I don't understand. I'm supposed to be beautiful. "
 ],
 farquaad: [
"That's enough. He's ready to talk.",
"Run, run, run, as fast as you can. You can't catch me. I'm the gingerbread man!",
"I'm not the monster here, you are. You and the rest of that fairy tale trash, poisoning my perfect world. Now, tell me! Where are the others?!",
"I've tried to be fair to you creatures. Now my patience has reached its end! Tell me or I'll...",
"All right then. Who's hiding them?",
'The muffin man?',
'Yes, I know the muffin man, who lives on Drury Lane?',
'The muffin man?',
"She's married to the muffin man...",
'Then what are you waiting for? Bring it in!',
'Evening. Mirror, mirror on the wall, is this not the most perfect kingdom of them all?',
'Uh, Thelonius. You were saying?',
'Three? One? Three?',
'Okay, okay, uh, number three!',
"Princess Fiona...she's perfect. All I have to do is just find someone who can go...",
"I'll do it.",
"Silence! I will make this Princess Fiona my queen, and Duloc will finally have the perfect king! Captain, assemble your finest men. We're going to have a tournament.",
'Brave knights. You are the best and brightest in all the land. Today one of you shall prove himself...',
"That champion shall have the honor-- no, no -- the privilege to go forth and rescue the lovely Princess Fiona from the fiery keep of the dragon. If for any reason the winner is unsuccessful, the first runner-up will take his place and so on and so forth. Some of you may die, but it's a sacrifice I am willing to make. Let the tournament begin!",
"Oh! What is that ? It's hideous!",
'Indeed. Knights, new plan! The one who kills the ogre will be named champion! Have it him!',
'No, I have a better idea. People of Duloc, I give you our champion!',
"Congratulations, ogre. You're won the honor of embarking on a great and noble quest.",
"Indeed. All right, ogre. I'll make you a deal. Go on this quest for me, and I'll give you your swamp back.",
'Down to the last slime-covered toadstool.',
'As good as gone.',
'Again, show me again. Mirror, mirror, show her to me. Show me the princess.',
'Very well, ogre. The deed to your swamp, cleared out, as agreed. Take it and go before I change my mind.',
'Forgive me, Princess, for startling you, but you startled me, for I have never seen such a radiant beauty before. I am Lord Farquaad.',
"Oh, that is so sweet. You don't have to waste good manners on the ogre. It's not like it has feelings.",
'Princess Fiona, beautiful, fair, flawless Fiona. I ask your hand in marriage. Will you be the perfect bride for the perfect groom ?',
"Excellent! I'll start the plans, for tomorrow we wed!",
"Oh, anxious, are you? You're right. The sooner, the better. There's so much to do! There's the caterer, the cake, the band, the guest list. Captain, round up some guests! There's so much to do!",
'Oh, now what does he want ?',
"Really, it's rude enough being alive when no one wants you, but showing up uninvited to a wedding...",
"Outrageous! Fiona, don't listen to him.",
'Oh, this is precious. The ogee has fallen in love with the princess! Oh, good Lord.',
'An ogre and a princess!',
`Who cares? It's preposterous! Fiona, my love, we're but a kiss away from our "happily ever after." Now kiss me! `,
"Ugh! It's disgusting! Guards! Guards! I order you to get that out of my sight now!",
'Get them! Get them both!',
'This hocus-pocus alters nothing. This marriage is binding, and that makes me king! See? See ?',
"Don't just stand there, you morons.",
"I'll make you regret the day we met. I'll see you drawn and quartered! You'll beg for death to save you!",
'And as for you, my wife...',
"I'll have you locked back in that tower for the rest of your days! I'm king!",
'I will have order! I will have perfection! I will have -- Aaaah! '
 ]
}

export default quotes